## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "https://mridu-portfolio.herokuapp.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
